apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: mdurovic-ambulance-ufe
spec:
  module-uri: http://mdurovic-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: mdurovic-ambulance-wl-app
      path: mdurovic-ambulance-wl
      title: Zoznam čakajúcich mdurovic
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /ui/mdurovic-ambulance-wl/
        - name: ambulance
          value: bobulova
        - name: api-uri
          value: /mdurovic-waiting-list-api
  preload: false
  proxy: true
  hash-suffix: v1alpha2
