apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: vaccinator-fe
spec:
  module-uri: http://vaccinator-fe.wac-hospital/build/vaccinator-fe.esm.js
  # module web komponentu pre tento mikroFE
  # - umiestnený v namespace wac-hospital
  navigation:
    - element: appointment-router    # element, ktorý bude vložený na stránku
      # pri navigácii na zoznam čakajúcich
      path: vaccinator-fe      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: BBM Projekt   # názov mikro aplikácie
      details: Balucha Bucko Macuga Projekt
      attributes:
        - name: base-path
          value: /ui/vaccinator-fe/
        - name: api-uri
          value: /vaccinator-be

  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
  # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
  # sa mení názov URL pre modul a tým je možné predísť problémom
  # s verziami vo vyrovnávacích pamätiach
