kind: Service
apiVersion: v1
metadata:
  name: mf-e-recipes-fe
spec:
  selector:
    pod: mf-e-recipes-fe-label
  ports:
    - name: http
      protocol: TCP
      port:
        80
      targetPort: http
