apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-ambulance-webapi
spec:
  replicas: 2
  selector:
      matchLabels:
        pod: ac-ambulance-webapi-label
  template:
      metadata:
        labels:
          pod: ac-ambulance-webapi-label
      spec:
        containers:
        - name: ac-ambulance-webapi-container
          image: jokkke/ambulance-webapi:1.0.0-21
          imagePullPolicy: Always
          ports:
          - name: webapi-port
            containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
          env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: mongodb_uri
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
