apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: tl-team-ufe

spec:   
  module-uri: http://tl-team-ufe.wac-hospital/build/equipment.esm.js
  navigation:
    - element: tl-equipment-app
      path: tl-equipment
      title: Tl-team Evidovanie inventáru tl
      details: Evidencia umiesnenia inventáru nemocníc
      attributes:
        - name: base-path
          value: /ui/tl-equipment/
        - name: api-uri
          value: /tl-equipment-api
  preload: false
  proxy: true
  hash-suffix: v1alpha2
