apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: stesch-ambulance-list
spec:   
  module-uri: http://stesch-ambulance-list.wac-hospital/build/ambulance-list.esm.js  # Meno service a namespace
                     # module web komponentu pre tento mikroFE 
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: stesch-ambulance-wl-app    # element, ktorý bude vložený na stránku 
                                    # pri navigácii na zoznam čakajúcich
      path: stesch-ambulance-wl      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Zoznam čakajúcich Stesch      # názov mikro aplikácie
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /ui/stesch-ambulance-wl/
        - name: ambulance
          value: bobulova        
        - name: api-uri
          value: /stesch-waiting-list-api
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti 
                                    # musí byť táto hodnota nastavená na true 
  hash-suffix: v1alpha2             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou 
                                    # sa mení názov URL pre modul a tým je možné predísť problémom 
                                    # s verziami vo vyrovnávacích pamätiach
