apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: covid19-testing-administration-ufe
spec:   
  module-uri: http://covid19-testing-administration-ufe.wac-hospital/build/covid19-testing-administration.esm.js  
  navigation:
    - element: covid19-testing-administration-app
      path: covid19-testing-administration
      title:  Sprava testovania na ochorenie COVID-19 - Mkukucka
      details:  Sprava testovania na ochorenie COVID-19
      attributes:
        - name: base-path
          value: /covid19-testing-administration/
        - name: api-uri
          value: /covid-list-api
        - name: mobile-testing-place
          value: spitalska
  preload: false
  proxy: true
  hash-suffix: v1alpha2