apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: t13-ambulance-t13
spec:   
  module-uri: http://t13-ambulance-t13.wac-hospital/build/ambulance-list.esm.js  
                     # module web komponentu pre tento mikroFE 
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: t13-ambulance-app    # element, ktorý bude vložený na stránku
                                    # pri navigácii na zoznam čakajúcich
      path: t13-ambulance      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Správa liekov (T13)      # názov mikro aplikácie
      details: Správa liekov v ambulancii, ich vydávanie pacientom a objednávanie v lekárni.
      attributes:                   
        - name: base-path
          value: /ui/t13-ambulance/
        - name: ambulance
          value: t13-ambulance
        - name: api-uri
          value: /t13-ambulance-api
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti 
                                    # musí byť táto hodnota nastavená na true 
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou 
                                    # sa mení názov URL pre modul a tým je možné predísť problémom 
                                    # s verziami vo vyrovnávacích pamätiach
