apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: ts-ambulance-ufe
spec:
  module-uri: http://ts-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: ts-ambulance-wl-app
      path: ts-ambulance-wl
      title: Zoznam čakajúcich msevcik
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: api-uri
          value: /ts-waiting-list-api
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha1
