apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: jm-ambulance-ufe
spec:   
  module-uri: http://jm-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: jm-ambulance-wl-app
      path: jm-ambulance-wl            
      title: Správa lôžkovej časti nemocnice Muller
      details: Spravuje lôžkovú časť nemocnice podľa jednotlivých oddelení a ich aktuálne a plánované obsadenie    
      attributes:                   
        - name: base-path
          value: /ui/jm-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false                    
  proxy: true                                           
  hash-suffix: v1alpha2                        

