apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: kali-project-ambulance
spec:
  module-uri: http://kali-project-ambulance.wac-hospital/build/medimanage.esm.js
  navigation:
    - element: router-app
      path: ambulance-kali
      title: Projekt Kali Ambulance # názov mikro aplikácie
      details: Pirky X Pablo X Dj Peter Pann
      attributes:
        - name: base-path
          value: /ui/ambulance-kali/
        - name: ambulance
          value: bobulova
        - name: api-uri
          value: /kali-waiting-list-api
  preload: false
  proxy: true
  hash-suffix: v1alpha2
