apiVersion: apps/v1
kind: Deployment
metadata:
  name: ij-jj-hospital-warehouse-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: ij-jj-hospital-warehouse-app-label
  template:
    metadata:
      labels: 
        pod: ij-jj-hospital-warehouse-app-label
    spec:
      containers:
      - name: ij-jj-hospital-warehouse-app-container
        image: ivanjatz/hospital-warehouse:1.0.0-66
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
            requests:               
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"
