name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          version: latest
      - shell: bash
        run: |
          kubectl kustomize _clusters/prod > prod.yaml
      - name: Run kubeconform
        uses: hermanbanken/kubeconform-action@v1
        with:          
          args: -schema-location default -schema-location '_pipelines/schemas/{{ .ResourceKind }}{{ .KindSuffix }}.json' prod.yaml
